# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propagators_loader.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1477, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vtk_widget = QVTKRenderWindowInteractor(self.centralwidget)
        self.vtk_widget.setGeometry(QtCore.QRect(230, 140, 871, 681))
        self.vtk_widget.setObjectName("vtk_widget")
        self.l_env = QtWidgets.QListWidget(self.centralwidget)
        self.l_env.setGeometry(QtCore.QRect(20, 140, 201, 441))
        self.l_env.setObjectName("l_env")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 120, 101, 16))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 0, 871, 108))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.line_dataset = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_dataset.setObjectName("line_dataset")
        self.gridLayout.addWidget(self.line_dataset, 0, 1, 1, 1)
        self.btn_dataset = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_dataset.setObjectName("btn_dataset")
        self.gridLayout.addWidget(self.btn_dataset, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.line_propagators = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_propagators.setObjectName("line_propagators")
        self.gridLayout.addWidget(self.line_propagators, 1, 1, 1, 1)
        self.btn_propagator = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_propagator.setObjectName("btn_propagator")
        self.gridLayout.addWidget(self.btn_propagator, 1, 2, 1, 1)
        self.line_descriptors = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_descriptors.setText("")
        self.line_descriptors.setObjectName("line_descriptors")
        self.gridLayout.addWidget(self.line_descriptors, 2, 1, 1, 1)
        self.btn_descriptors = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_descriptors.setObjectName("btn_descriptors")
        self.gridLayout.addWidget(self.btn_descriptors, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 600, 101, 16))
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.l_interactions = QtWidgets.QListWidget(self.centralwidget)
        self.l_interactions.setGeometry(QtCore.QRect(20, 620, 201, 201))
        self.l_interactions.setObjectName("l_interactions")
        self.btn_view_interaction = QtWidgets.QPushButton(self.centralwidget)
        self.btn_view_interaction.setEnabled(False)
        self.btn_view_interaction.setGeometry(QtCore.QRect(1410, 250, 41, 22))
        self.btn_view_interaction.setObjectName("btn_view_interaction")
        self.tree_train = QtWidgets.QTreeView(self.centralwidget)
        self.tree_train.setGeometry(QtCore.QRect(1110, 300, 351, 401))
        self.tree_train.setAlternatingRowColors(True)
        self.tree_train.setAutoExpandDelay(-1)
        self.tree_train.setIndentation(10)
        self.tree_train.setItemsExpandable(True)
        self.tree_train.setObjectName("tree_train")
        self.tree_propagation = QtWidgets.QTreeView(self.centralwidget)
        self.tree_propagation.setGeometry(QtCore.QRect(1110, 710, 351, 111))
        self.tree_propagation.setAlternatingRowColors(True)
        self.tree_propagation.setAutoExpandDelay(-1)
        self.tree_propagation.setIndentation(10)
        self.tree_propagation.setItemsExpandable(True)
        self.tree_propagation.setObjectName("tree_propagation")
        self.chk_on_gray_env = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_on_gray_env.setGeometry(QtCore.QRect(920, 10, 181, 20))
        self.chk_on_gray_env.setObjectName("chk_on_gray_env")
        self.vtk_interaction = QVTKRenderWindowInteractor(self.centralwidget)
        self.vtk_interaction.setEnabled(True)
        self.vtk_interaction.setGeometry(QtCore.QRect(1110, 0, 351, 281))
        self.vtk_interaction.setObjectName("vtk_interaction")
        self.btn_add_sample = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_sample.setEnabled(False)
        self.btn_add_sample.setGeometry(QtCore.QRect(1000, 760, 91, 22))
        self.btn_add_sample.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_add_sample.setObjectName("btn_add_sample")
        self.btn_show_samples = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show_samples.setEnabled(False)
        self.btn_show_samples.setGeometry(QtCore.QRect(1000, 790, 91, 23))
        self.btn_show_samples.setObjectName("btn_show_samples")
        self.chk_on_tested_points = QtWidgets.QCheckBox(self.centralwidget)
        self.chk_on_tested_points.setGeometry(QtCore.QRect(920, 40, 181, 20))
        self.chk_on_tested_points.setIconSize(QtCore.QSize(16, 27))
        self.chk_on_tested_points.setChecked(True)
        self.chk_on_tested_points.setAutoRepeatDelay(300)
        self.chk_on_tested_points.setObjectName("chk_on_tested_points")
        self.vtk_interaction.raise_()
        self.vtk_widget.raise_()
        self.l_env.raise_()
        self.label.raise_()
        self.layoutWidget.raise_()
        self.label_6.raise_()
        self.l_interactions.raise_()
        self.btn_view_interaction.raise_()
        self.tree_train.raise_()
        self.tree_propagation.raise_()
        self.btn_show_samples.raise_()
        self.btn_add_sample.raise_()
        self.chk_on_tested_points.raise_()
        self.chk_on_gray_env.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1477, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vizualizing propagation"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Environment:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Dataset</span></p></body></html>"))
        self.btn_dataset.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Propagators</span></p></body></html>"))
        self.btn_propagator.setText(_translate("MainWindow", "..."))
        self.btn_descriptors.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Descriptors</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Interactions:</span></p></body></html>"))
        self.btn_view_interaction.setText(_translate("MainWindow", "Zoom"))
        self.chk_on_gray_env.setText(_translate("MainWindow", "environment in gray color"))
        self.btn_add_sample.setText(_translate("MainWindow", "Add sample"))
        self.btn_show_samples.setText(_translate("MainWindow", "Show samples"))
        self.chk_on_tested_points.setText(_translate("MainWindow", "tested points"))

from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

